# Generated by Django 5.2.17 on 2026-08-27 22:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Studio Name', help_text='Shown in the site header, page titles and outgoing email.', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Custom CAD design and 3D printing', help_text='One line, shown under the business name on the home page.', max_length=200)),
                ('support_email', models.EmailField(default='hello@example.com', help_text='Where clients are told to reach you. Not the sending address.', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('pickup_address', models.TextField(blank=True, help_text='Shown to clients who choose pickup instead of delivery.')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0725'), help_text='Sales tax as a decimal rate. 0.0725 is 7.25%.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('delivery_base_fee_cents', models.PositiveIntegerField(default=1500, help_text='Flat courier fee in cents, added to delivery orders.')),
                ('max_print_files', models.PositiveSmallIntegerField(default=10, help_text='Maximum distinct model files on one printing order.')),
                ('max_item_quantity', models.PositiveSmallIntegerField(default=100, help_text='Maximum quantity of any single item.')),
                ('max_upload_mb', models.PositiveSmallIntegerField(default=100, help_text='Largest accepted single file, in megabytes.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business configuration',
                'verbose_name_plural': 'Business configuration',
            },
        ),
    ]
